using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Datos.Models;
using System.Collections.Generic;
using System.Linq;

namespace Datos.Seeders
{
    public static class CiudadSeeder
    {
        public static void SeedCiudades(this EntityTypeBuilder<Ciudad> modelBuilder)
        {

            modelBuilder.HasData(
                 new Ciudad { Id = 1, Nombre = "Cuenca", IdProvincia = 1 },
                new Ciudad { Id = 2, Nombre = "Girón", IdProvincia = 1 },
                new Ciudad { Id = 3, Nombre = "Gualaceo", IdProvincia = 1 },
                new Ciudad { Id = 4, Nombre = "Nabón", IdProvincia = 1 },
                new Ciudad { Id = 5, Nombre = "Paute", IdProvincia = 1 },
                new Ciudad { Id = 6, Nombre = "Pucará", IdProvincia = 1 },
                new Ciudad { Id = 7, Nombre = "San Fernando", IdProvincia = 1 },
                new Ciudad { Id = 8, Nombre = "Santa Isabel", IdProvincia = 1 },
                new Ciudad { Id = 9, Nombre = "Sigsig", IdProvincia = 1 },
                new Ciudad { Id = 10, Nombre = "Oña", IdProvincia = 1 },
                new Ciudad { Id = 11, Nombre = "Chordeleg", IdProvincia = 1 },
                new Ciudad { Id = 12, Nombre = "El Pan", IdProvincia = 1 },
                new Ciudad { Id = 13, Nombre = "Sevilla de Oro", IdProvincia = 1 },
                new Ciudad { Id = 14, Nombre = "Guachapala", IdProvincia = 1 },
                new Ciudad { Id = 15, Nombre = "Camilo Ponce Enríquez", IdProvincia = 1 },
                new Ciudad { Id = 16, Nombre = "Guaranda", IdProvincia = 2 },
                new Ciudad { Id = 17, Nombre = "Chillanes", IdProvincia = 2 },
                new Ciudad { Id = 18, Nombre = "Chimbo", IdProvincia = 2 },
                new Ciudad { Id = 19, Nombre = "Echeandía", IdProvincia = 2 },
                new Ciudad { Id = 20, Nombre = "San Miguel", IdProvincia = 2 },
                new Ciudad { Id = 21, Nombre = "Caluma", IdProvincia = 2 },
                new Ciudad { Id = 22, Nombre = "Las Naves", IdProvincia = 2 },
                new Ciudad { Id = 23, Nombre = "Azogues", IdProvincia = 3 },
                new Ciudad { Id = 24, Nombre = "Biblián", IdProvincia = 3 },
                new Ciudad { Id = 25, Nombre = "Cañar", IdProvincia = 3 },
                new Ciudad { Id = 26, Nombre = "La Troncal", IdProvincia = 3 },
                new Ciudad { Id = 27, Nombre = "El Tambo", IdProvincia = 3 },
                new Ciudad { Id = 28, Nombre = "Déleg", IdProvincia = 3 },
                new Ciudad { Id = 29, Nombre = "Suscal", IdProvincia = 3 },
                new Ciudad { Id = 30, Nombre = "Tulcán", IdProvincia = 4 },
                new Ciudad { Id = 31, Nombre = "Bolívar", IdProvincia = 4 },
                new Ciudad { Id = 32, Nombre = "Espejo", IdProvincia = 4 },
                new Ciudad { Id = 33, Nombre = "Mira", IdProvincia = 4 },
                new Ciudad { Id = 34, Nombre = "Montúfar", IdProvincia = 4 },
                new Ciudad { Id = 35, Nombre = "San Pedro de Huaca", IdProvincia = 4 },
                new Ciudad { Id = 36, Nombre = "Latacunga", IdProvincia = 5 },
                new Ciudad { Id = 37, Nombre = "La Maná", IdProvincia = 5 },
                new Ciudad { Id = 38, Nombre = "Pangua", IdProvincia = 5 },
                new Ciudad { Id = 39, Nombre = "Pujilí", IdProvincia = 5 },
                new Ciudad { Id = 40, Nombre = "Salcedo", IdProvincia = 5 },
                new Ciudad { Id = 41, Nombre = "Saquisilí", IdProvincia = 5 },
                new Ciudad { Id = 42, Nombre = "Sigchos", IdProvincia = 5 },
                new Ciudad { Id = 43, Nombre = "Riobamba", IdProvincia = 6 },
                new Ciudad { Id = 44, Nombre = "Alausí", IdProvincia = 6 },
                new Ciudad { Id = 45, Nombre = "Colta", IdProvincia = 6 },
                new Ciudad { Id = 46, Nombre = "Chambo", IdProvincia = 6 },
                new Ciudad { Id = 47, Nombre = "Chunchi", IdProvincia = 6 },
                new Ciudad { Id = 48, Nombre = "Guamote", IdProvincia = 6 },
                new Ciudad { Id = 49, Nombre = "Guano", IdProvincia = 6 },
                new Ciudad { Id = 50, Nombre = "Pallatanga", IdProvincia = 6 },
                new Ciudad { Id = 51, Nombre = "Penipe", IdProvincia = 6 },
                new Ciudad { Id = 52, Nombre = "Cumandá", IdProvincia = 6 },
                new Ciudad { Id = 53, Nombre = "Machala", IdProvincia = 7 },
                new Ciudad { Id = 54, Nombre = "Arenillas", IdProvincia = 7 },
                new Ciudad { Id = 55, Nombre = "Atahualpa", IdProvincia = 7 },
                new Ciudad { Id = 56, Nombre = "Balsas", IdProvincia = 7 },
                new Ciudad { Id = 57, Nombre = "Chilla", IdProvincia = 7 },
                new Ciudad { Id = 58, Nombre = "El Guabo", IdProvincia = 7 },
                new Ciudad { Id = 59, Nombre = "Huaquillas", IdProvincia = 7 },
                new Ciudad { Id = 60, Nombre = "Marcabelí", IdProvincia = 7 },
                new Ciudad { Id = 61, Nombre = "Pasaje", IdProvincia = 7 },
                new Ciudad { Id = 62, Nombre = "Piñas", IdProvincia = 7 },
                new Ciudad { Id = 63, Nombre = "Portovelo", IdProvincia = 7 },
                new Ciudad { Id = 64, Nombre = "Santa Rosa", IdProvincia = 7 },
                new Ciudad { Id = 65, Nombre = "Zaruma", IdProvincia = 7 },
                new Ciudad { Id = 66, Nombre = "Las Lajas", IdProvincia = 7 },
                new Ciudad { Id = 67, Nombre = "Esmeraldas", IdProvincia = 8 },
                new Ciudad { Id = 68, Nombre = "Eloy Alfaro", IdProvincia = 8 },
                new Ciudad { Id = 69, Nombre = "Muisne", IdProvincia = 8 },
                new Ciudad { Id = 70, Nombre = "Quinindé", IdProvincia = 8 },
                new Ciudad { Id = 71, Nombre = "San Lorenzo", IdProvincia = 8 },
                new Ciudad { Id = 72, Nombre = "Atacames", IdProvincia = 8 },
                new Ciudad { Id = 73, Nombre = "Rioverde", IdProvincia = 8 },
                new Ciudad { Id = 74, Nombre = "La Concordia", IdProvincia = 8 },
                new Ciudad { Id = 75, Nombre = "Guayaquil", IdProvincia = 9 },
                new Ciudad { Id = 76, Nombre = "Alfredo Baquerizo Moreno (Juján)", IdProvincia = 9 },
                new Ciudad { Id = 77, Nombre = "Balao", IdProvincia = 9 },
                new Ciudad { Id = 78, Nombre = "Balzar", IdProvincia = 9 },
                new Ciudad { Id = 79, Nombre = "Colimes", IdProvincia = 9 },
                new Ciudad { Id = 80, Nombre = "Daule", IdProvincia = 9 },
                new Ciudad { Id = 81, Nombre = "Durán", IdProvincia = 9 },
                new Ciudad { Id = 82, Nombre = "El Empalme", IdProvincia = 9 },
                new Ciudad { Id = 83, Nombre = "El Triunfo", IdProvincia = 9 },
                new Ciudad { Id = 84, Nombre = "Milagro", IdProvincia = 9 },
                new Ciudad { Id = 85, Nombre = "Naranjal", IdProvincia = 9 },
                new Ciudad { Id = 86, Nombre = "Naranjito", IdProvincia = 9 },
                new Ciudad { Id = 87, Nombre = "Palestina", IdProvincia = 9 },
                new Ciudad { Id = 88, Nombre = "Pedro Carbo", IdProvincia = 9 },
                new Ciudad { Id = 89, Nombre = "Samborondón", IdProvincia = 9 },
                new Ciudad { Id = 90, Nombre = "Santa Lucía", IdProvincia = 9 },
                new Ciudad { Id = 91, Nombre = "Salitre (Urbina Jado)", IdProvincia = 9 },
                new Ciudad { Id = 92, Nombre = "San Jacinto de Yaguachi", IdProvincia = 9 },
                new Ciudad { Id = 93, Nombre = "Playas", IdProvincia = 9 },
                new Ciudad { Id = 94, Nombre = "Simón Bolívar", IdProvincia = 9 },
                new Ciudad { Id = 95, Nombre = "Coronel Marcelino Maridueña", IdProvincia = 9 },
                new Ciudad { Id = 96, Nombre = "Lomas de Sargentillo", IdProvincia = 9 },
                new Ciudad { Id = 97, Nombre = "Nobol", IdProvincia = 9 },
                new Ciudad { Id = 98, Nombre = "General Antonio Elizalde", IdProvincia = 9 },
                new Ciudad { Id = 99, Nombre = "Isidro Ayora", IdProvincia = 9 },
                new Ciudad { Id = 100, Nombre = "Ibarra", IdProvincia = 10 },
                new Ciudad { Id = 101, Nombre = "Antonio Ante", IdProvincia = 10 },
                new Ciudad { Id = 102, Nombre = "Cotacachi", IdProvincia = 10 },
                new Ciudad { Id = 103, Nombre = "Otavalo", IdProvincia = 10 },
                new Ciudad { Id = 104, Nombre = "Pimampiro", IdProvincia = 10 },
                new Ciudad { Id = 105, Nombre = "San Miguel de Urcuquí", IdProvincia = 10 },
                new Ciudad { Id = 106, Nombre = "Loja", IdProvincia = 11 },
                new Ciudad { Id = 107, Nombre = "Calvas", IdProvincia = 11 },
                new Ciudad { Id = 108, Nombre = "Catamayo", IdProvincia = 11 },
                new Ciudad { Id = 109, Nombre = "Celica", IdProvincia = 11 },
                new Ciudad { Id = 110, Nombre = "Chaguarpamba", IdProvincia = 11 },
                new Ciudad { Id = 111, Nombre = "Espíndola", IdProvincia = 11 },
                new Ciudad { Id = 112, Nombre = "Gonzanamá", IdProvincia = 11 },
                new Ciudad { Id = 113, Nombre = "Macará", IdProvincia = 11 },
                new Ciudad { Id = 114, Nombre = "Paltas", IdProvincia = 11 },
                new Ciudad { Id = 115, Nombre = "Puyango", IdProvincia = 11 },
                new Ciudad { Id = 116, Nombre = "Saraguro", IdProvincia = 11 },
                new Ciudad { Id = 117, Nombre = "Sozoranga", IdProvincia = 11 },
                new Ciudad { Id = 118, Nombre = "Zapotillo", IdProvincia = 11 },
                new Ciudad { Id = 119, Nombre = "Pindal", IdProvincia = 11 },
                new Ciudad { Id = 120, Nombre = "Quilanga", IdProvincia = 11 },
                new Ciudad { Id = 121, Nombre = "Olmedo", IdProvincia = 11 },
                new Ciudad { Id = 122, Nombre = "Babahoyo", IdProvincia = 12 },
                new Ciudad { Id = 123, Nombre = "Baba", IdProvincia = 12 },
                new Ciudad { Id = 124, Nombre = "Montalvo", IdProvincia = 12 },
                new Ciudad { Id = 125, Nombre = "Puebloviejo", IdProvincia = 12 },
                new Ciudad { Id = 126, Nombre = "Quevedo", IdProvincia = 12 },
                new Ciudad { Id = 127, Nombre = "Urdaneta", IdProvincia = 12 },
                new Ciudad { Id = 128, Nombre = "Ventanas", IdProvincia = 12 },
                new Ciudad { Id = 129, Nombre = "Vínces", IdProvincia = 12 },
                new Ciudad { Id = 130, Nombre = "Palenque", IdProvincia = 12 },
                new Ciudad { Id = 131, Nombre = "Buena Fé", IdProvincia = 12 },
                new Ciudad { Id = 132, Nombre = "Valencia", IdProvincia = 12 },
                new Ciudad { Id = 133, Nombre = "Mocache", IdProvincia = 12 },
                new Ciudad { Id = 134, Nombre = "Quinsaloma", IdProvincia = 12 },
                new Ciudad { Id = 135, Nombre = "Portoviejo", IdProvincia = 13 },
                new Ciudad { Id = 136, Nombre = "Bolívar", IdProvincia = 13 },
                new Ciudad { Id = 137, Nombre = "Chone", IdProvincia = 13 },
                new Ciudad { Id = 138, Nombre = "El Carmen", IdProvincia = 13 },
                new Ciudad { Id = 139, Nombre = "Flavio Alfaro", IdProvincia = 13 },
                new Ciudad { Id = 140, Nombre = "Jipijapa", IdProvincia = 13 },
                new Ciudad { Id = 141, Nombre = "Junín", IdProvincia = 13 },
                new Ciudad { Id = 142, Nombre = "Manta", IdProvincia = 13 },
                new Ciudad { Id = 143, Nombre = "Montecristi", IdProvincia = 13 },
                new Ciudad { Id = 144, Nombre = "Paján", IdProvincia = 13 },
                new Ciudad { Id = 145, Nombre = "Pichincha", IdProvincia = 13 },
                new Ciudad { Id = 146, Nombre = "Rocafuerte", IdProvincia = 13 },
                new Ciudad { Id = 147, Nombre = "Santa Ana", IdProvincia = 13 },
                new Ciudad { Id = 148, Nombre = "Sucre", IdProvincia = 13 },
                new Ciudad { Id = 149, Nombre = "Tosagua", IdProvincia = 13 },
                new Ciudad { Id = 150, Nombre = "24 de Mayo", IdProvincia = 13 },
                new Ciudad { Id = 151, Nombre = "Pedernales", IdProvincia = 13 },
                new Ciudad { Id = 152, Nombre = "Olmedo", IdProvincia = 13 },
                new Ciudad { Id = 153, Nombre = "Puerto López", IdProvincia = 13 },
                new Ciudad { Id = 154, Nombre = "Jama", IdProvincia = 13 },
                new Ciudad { Id = 155, Nombre = "Jaramijó", IdProvincia = 13 },
                new Ciudad { Id = 156, Nombre = "San Vicente", IdProvincia = 13 },
                new Ciudad { Id = 157, Nombre = "Morona", IdProvincia = 14 },
                new Ciudad { Id = 158, Nombre = "Gualaquiza", IdProvincia = 14 },
                new Ciudad { Id = 159, Nombre = "Limón Indanza", IdProvincia = 14 },
                new Ciudad { Id = 160, Nombre = "Palora", IdProvincia = 14 },
                new Ciudad { Id = 161, Nombre = "Santiago", IdProvincia = 14 },
                new Ciudad { Id = 162, Nombre = "Sucúa", IdProvincia = 14 },
                new Ciudad { Id = 163, Nombre = "Huamboya", IdProvincia = 14 },
                new Ciudad { Id = 164, Nombre = "San Juan Bosco", IdProvincia = 14 },
                new Ciudad { Id = 165, Nombre = "Taisha", IdProvincia = 14 },
                new Ciudad { Id = 166, Nombre = "Logroño", IdProvincia = 14 },
                new Ciudad { Id = 167, Nombre = "Pablo Sexto", IdProvincia = 14 },
                new Ciudad { Id = 168, Nombre = "Tiwintza", IdProvincia = 14 },
                new Ciudad { Id = 169, Nombre = "Tena", IdProvincia = 15 },
                new Ciudad { Id = 170, Nombre = "Archidona", IdProvincia = 15 },
                new Ciudad { Id = 171, Nombre = "El Chaco", IdProvincia = 15 },
                new Ciudad { Id = 172, Nombre = "Quijos", IdProvincia = 15 },
                new Ciudad { Id = 173, Nombre = "Carlos Julio Arosemena Tola", IdProvincia = 15 },
                new Ciudad { Id = 174, Nombre = "Pastaza", IdProvincia = 16 },
                new Ciudad { Id = 175, Nombre = "Mera", IdProvincia = 16 },
                new Ciudad { Id = 176, Nombre = "Santa Clara", IdProvincia = 16 },
              new Ciudad { Id = 177, Nombre = "Arajuno", IdProvincia = 16 },
                new Ciudad { Id = 179, Nombre = "Cayambe", IdProvincia = 17 },
                new Ciudad { Id = 180, Nombre = "Mejia", IdProvincia = 17 },
                new Ciudad { Id = 181, Nombre = "Pedro Moncayo", IdProvincia = 17 },
                new Ciudad { Id = 182, Nombre = "Rumiñahui", IdProvincia = 17 },
                new Ciudad { Id = 183, Nombre = "San Miguel de Los Bancos", IdProvincia = 17 },
                new Ciudad { Id = 184, Nombre = "Pedro Vicente Maldonado", IdProvincia = 17 },
                new Ciudad { Id = 185, Nombre = "Puerto Quito", IdProvincia = 17 },
                new Ciudad { Id = 186, Nombre = "Ambato", IdProvincia = 18 },
                new Ciudad { Id = 187, Nombre = "Baños de Agua Santa", IdProvincia = 18 },
                new Ciudad { Id = 188, Nombre = "Cevallos", IdProvincia = 18 },
                new Ciudad { Id = 189, Nombre = "Mocha", IdProvincia = 18 },
                new Ciudad { Id = 190, Nombre = "Patate", IdProvincia = 18 },
                new Ciudad { Id = 191, Nombre = "Quero", IdProvincia = 18 },
                new Ciudad { Id = 192, Nombre = "San Pedro de Pelileo", IdProvincia = 18 },
                new Ciudad { Id = 193, Nombre = "Santiago de Píllaro", IdProvincia = 18 },
                new Ciudad { Id = 194, Nombre = "Tisaleo", IdProvincia = 18 },
                new Ciudad { Id = 195, Nombre = "Zamora", IdProvincia = 19 },
                new Ciudad { Id = 196, Nombre = "Chinchipe", IdProvincia = 19 },
                new Ciudad { Id = 197, Nombre = "Nangaritza", IdProvincia = 19 },
                new Ciudad { Id = 198, Nombre = "Yacuambi", IdProvincia = 19 },
                new Ciudad { Id = 199, Nombre = "Yantzaza (Yanzatza)", IdProvincia = 19 },
                new Ciudad { Id = 200, Nombre = "El Pangui", IdProvincia = 19 },
                new Ciudad { Id = 201, Nombre = "Centinela del Cóndor", IdProvincia = 19 },
                new Ciudad { Id = 202, Nombre = "Palanda", IdProvincia = 19 },
                new Ciudad { Id = 203, Nombre = "Paquisha", IdProvincia = 19 },
                new Ciudad { Id = 204, Nombre = "San Cristóbal", IdProvincia = 20 },
                new Ciudad { Id = 205, Nombre = "Isabela", IdProvincia = 20 },
                new Ciudad { Id = 206, Nombre = "Santa Cruz", IdProvincia = 20 },
                new Ciudad { Id = 207, Nombre = "Lago Agrio", IdProvincia = 21 },
                new Ciudad { Id = 208, Nombre = "Gonzalo Pizarro", IdProvincia = 21 },
                new Ciudad { Id = 209, Nombre = "Putumayo", IdProvincia = 21 },
                new Ciudad { Id = 210, Nombre = "Shushufindi", IdProvincia = 21 },
                new Ciudad { Id = 211, Nombre = "Sucumbíos", IdProvincia = 21 },
                new Ciudad { Id = 212, Nombre = "Cascales", IdProvincia = 21 },
                new Ciudad { Id = 213, Nombre = "Cuyabeno", IdProvincia = 21 },
                new Ciudad { Id = 214, Nombre = "Orellana", IdProvincia = 22 },
                new Ciudad { Id = 215, Nombre = "Aguarico", IdProvincia = 22 },
                new Ciudad { Id = 216, Nombre = "La Joya de Los Sachas", IdProvincia = 22 },
                new Ciudad { Id = 217, Nombre = "Loreto", IdProvincia = 22 },
                new Ciudad { Id = 218, Nombre = "Santo Domingo", IdProvincia = 23 },
                new Ciudad { Id = 219, Nombre = "Santa Elena", IdProvincia = 24 },
                new Ciudad { Id = 220, Nombre = "La Libertad", IdProvincia = 24 },
                new Ciudad { Id = 221, Nombre = "Salinas", IdProvincia = 24 },
                new Ciudad { Id = 222, Nombre = "Las Golondrinas", IdProvincia = 25 },
                new Ciudad { Id = 223, Nombre = "Manga del Cura", IdProvincia = 25 },
                new Ciudad { Id = 224, Nombre = "El Piedrero", IdProvincia = 25 }
            );
        }

    }
}
